
// Objective-C API for talking to the following Go packages
//
//	champo.com/panic
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Panicker_FRAMEWORK_H__
#define __Panicker_FRAMEWORK_H__

#include "Panicker.objc.h"
#include "Universe.objc.h"

#endif
